# travis-ci.org definition for python-patterns build
language: python

sudo: false

python:
  - "3.5"
  - "3.6"

cache:
  - pip

install:
  - travis_retry pip install -q coveralls codecov

script:
  - cd python-patterns/src
  # Run tests
  - nosetests --with-doctest --with-cov  --cover-erase --cover-branches --cover-package .

after_success:
  - coveralls
  - codecov
